;; Problema modificado
(define (problem menu-ejemplo)
  (:domain menu-semanal)

  (:objects
  lunes martes miercoles jueves viernes - dia
  ensalada sopa paella crema pasta arroz - plato
  pollo merluza lasagna fabada calamar tortilla tortilla_caducada - plato
  gazpacho sopa_bolonesa quiche salmon bruschetta tortilla_espanola risotto hamburguesa ceviche gazpacho_vegano curry - plato
  sopa carne pescado pasta ensalada arroz marisco huevo vegetariano - tipo
)

(:init

  (= (precio_total) 0)

  (es_lunes lunes)

  (menu_dia lunes)
  (menu_dia martes)
  (menu_dia miercoles)
  (menu_dia jueves)
  (menu_dia viernes)

  (es_primero ensalada)
  (es_primero sopa)
  (es_primero paella)
  (es_primero crema)
  (es_primero pasta)
  (es_primero arroz)
  (es_primero gazpacho)
  (es_primero sopa_bolonesa)
  (es_primero bruschetta)
  (es_primero gazpacho_vegano)

  (es_segundo pollo)
  (es_segundo merluza)
  (es_segundo lasagna)
  (es_segundo fabada)
  (es_segundo calamar)
  (es_segundo tortilla)
  (es_segundo tortilla_caducada)
  (es_segundo quiche)
  (es_segundo salmon)
  (es_segundo tortilla_espanola)
  (es_segundo risotto)
  (es_segundo hamburguesa)
  (es_segundo ceviche)
  (es_segundo curry)

  (tipo ensalada ensalada)
  (tipo sopa sopa)
  (tipo paella arroz)
  (tipo crema sopa)
  (tipo pasta pasta)
  (tipo arroz arroz)
  (tipo pollo carne)
  (tipo merluza pescado)
  (tipo lasagna pasta)
  (tipo fabada carne)
  (tipo calamar marisco)
  (tipo tortilla huevo)
  (tipo tortilla_caducada huevo)

  (tipo gazpacho sopa)
  (tipo sopa_bolonesa sopa)
  (tipo quiche huevo)
  (tipo salmon pescado)
  (tipo bruschetta vegetariano)
  (tipo tortilla_espanola huevo)
  (tipo risotto arroz)
  (tipo hamburguesa carne)
  (tipo ceviche marisco)
  (tipo gazpacho_vegano vegetariano)
  (tipo curry carne)

  (incompatible paella fabada)
  (incompatible sopa fabada)

  (anterior martes lunes)
  (anterior miercoles martes)
  (anterior jueves miercoles)
  (anterior viernes jueves)

  (plato_obligatorio_primero jueves paella)
  (plato_obligatorio_primero lunes crema)
  (plato_obligatorio_segundo viernes lasagna)

  (= (calorias ensalada) 300)
  (= (calorias sopa) 250)
  (= (calorias paella) 700)
  (= (calorias crema) 450)
  (= (calorias pasta) 500)
  (= (calorias arroz) 650)
  (= (calorias pollo) 600)
  (= (calorias merluza) 400)
  (= (calorias lasagna) 800)
  (= (calorias fabada) 900)
  (= (calorias calamar) 550)
  (= (calorias tortilla) 400)
  (= (calorias tortilla_caducada) 400)

  (= (calorias gazpacho) 200)
  (= (calorias sopa_bolonesa) 350)
  (= (calorias quiche) 600)
  (= (calorias salmon) 450)
  (= (calorias bruschetta) 300)
  (= (calorias tortilla_espanola) 400)
  (= (calorias risotto) 550)
  (= (calorias hamburguesa) 700)
  (= (calorias ceviche) 350)
  (= (calorias gazpacho_vegano) 180)
  (= (calorias curry) 650)

  (= (precio ensalada) 3)
  (= (precio sopa) 2)
  (= (precio paella) 5)
  (= (precio crema) 3)
  (= (precio pasta) 4)
  (= (precio arroz) 300)
  (= (precio pollo) 4)
  (= (precio merluza) 5)
  (= (precio lasagna) 6)
  (= (precio fabada) 100)
  (= (precio calamar) 6)
  (= (precio tortilla) 3)
  (= (precio tortilla_caducada) 100)

  (= (precio gazpacho) 3)
  (= (precio sopa_bolonesa) 4)
  (= (precio quiche) 5)
  (= (precio salmon) 6)
  (= (precio bruschetta) 4)
  (= (precio tortilla_espanola) 4)
  (= (precio risotto) 5)
  (= (precio hamburguesa) 7)
  (= (precio ceviche) 300)
  (= (precio gazpacho_vegano) 3)
  (= (precio curry) 6)
)

  (:goal (and
  (menu-asignado lunes)
  (menu-asignado martes)
  (menu-asignado miercoles)
  (menu-asignado jueves)
  (menu-asignado viernes)
  
  (forall (?d - dia ?p - plato)
  (imply (plato_obligatorio_primero ?d ?p)
         (exists (?s - plato)
            (asignado ?d ?p ?s)))
  )

  (forall (?d - dia ?p - plato)
  (imply (plato_obligatorio_segundo ?d ?p)
         (exists (?s - plato)
            (asignado ?d ?s ?p)))
  )
  )
  )
  
(:metric minimize (precio_total))

)
