(define (domain menu-semanal)
  (:requirements :strips :typing)
  (:types plato dia tipo)
  (:predicates
    (es_primero ?p - plato)
    (es_segundo ?p - plato)
    (incompatible ?p1 - plato ?p2 - plato)
    (asignado ?d - dia ?p1 - plato ?p2 - plato)
    (menu_dia ?d - dia)
    (usado ?p - plato)
    (menu-asignado ?d - dia)
    (tipo ?p - plato ?t - tipo)
    (tipo_primero_asignado ?d - dia ?t - tipo)
    (tipo_segundo_asignado ?d - dia ?t - tipo)
    (anterior ?d - dia ?d_prev - dia)
    (es_lunes ?d - dia)
  )

  (:action asignar_menu_lunes
    :parameters (?d - dia ?p1 - plato ?p2 - plato ?t1 - tipo ?t2 - tipo)
    :precondition (and
      (es_lunes ?d)
      (es_primero ?p1)
      (es_segundo ?p2)
      (menu_dia ?d)
      (tipo ?p1 ?t1)
      (tipo ?p2 ?t2)
      (not (incompatible ?p1 ?p2))
      (not (usado ?p1))
      (not (usado ?p2))
      (not (menu-asignado ?d))
    )
    :effect (and
      (asignado ?d ?p1 ?p2)
      (usado ?p1)
      (usado ?p2)
      (menu-asignado ?d)
      (tipo_primero_asignado ?d ?t1)
      (tipo_segundo_asignado ?d ?t2)
    )
  )

  (:action asignar_menu
    :parameters (?d - dia ?p1 - plato ?p2 - plato ?t1 - tipo ?t2 - tipo ?d_prev - dia)
    :precondition (and
      (es_primero ?p1)
      (es_segundo ?p2)
      (menu_dia ?d)
      (tipo ?p1 ?t1)
      (tipo ?p2 ?t2)
      (anterior ?d ?d_prev)
      (not (incompatible ?p1 ?p2))
      (not (usado ?p1))
      (not (usado ?p2))
      (not (menu-asignado ?d))
      (not (tipo_primero_asignado ?d_prev ?t1))
      (not (tipo_segundo_asignado ?d_prev ?t2))
    )
    :effect (and
      (asignado ?d ?p1 ?p2)
      (usado ?p1)
      (usado ?p2)
      (menu-asignado ?d)
      (tipo_primero_asignado ?d ?t1)
      (tipo_segundo_asignado ?d ?t2)
    )
  )
)